name: Build wheels

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.target.os }} 
    runs-on: ${{ matrix.target.os }} 
    strategy:
      matrix:
        target:
          - os: "ubuntu-20.04"
            python-version: "3.10"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.target.python-version }}
      uses: actions/setup-python@v4.0.0
      with:
        python-version: ${{ matrix.target.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
    - name: Building wheels for ${{ matrix.target.os }} 
      run: |
        python -m build --wheel
    - uses: actions/upload-artifact@v3
      with:
        path: ./dist/*.whl 
