name: Code Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.8"
            toxenv: "py38"
          - version: "3.9"
            toxenv: "py39"
          - version: "3.10"
            toxenv: "py310"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python.version }}
      uses: actions/setup-python@v4.0.0
      with:
        python-version: ${{ matrix.python.version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Testing code with pytest
      run: |
        tox -e ${{ matrix.python.toxenv }}
